const express = require('express');
const sqlTestRouter = require('./src/routes/sqlTestRouter');
const authRouter = require('./src/routes/authRouter');
const swaggerUi = require('swagger-ui-express');
const swaggerDocument = require('./swagger.json');

const app = express();
const PORT = 4000;

const swaggerJsdoc = require('swagger-jsdoc');

const options = {
  swaggerDefinition: {
    // Like the one described here: https://swagger.io/specification/#infoObject
    info: {
      title: 'Test API',
      version: '1.0.0',
      description: 'Test Express API with autogenerated swagger doc',
    },
  },
  // List of files to be processes. You can also set globs './routes/*.js'
  apis: ['./src/routes/*.js'],
};

const specs = swaggerJsdoc(options);


app.use(express.urlencoded());
app.use(express.json()); 

// routes(app);
app.use('/api/auth', authRouter);
app.use('/api/sqltest', sqlTestRouter);

app.get('/', (req, res) =>
    res.send(`Store server running on port ${PORT}`)
);

app.get('/welcome', (req, res) =>
    res.send(`welcome to globefeng's nodejs api`)
);

app.use('/swagger', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
// app.use('/swagger', swaggerUi.serve, swaggerUi.setup(specs));

app.listen(PORT, () => 
    console.log(`Your server is running on port ${PORT}`)
);
